"""Stub file for custom_components/reflex_mapcn/mapcn.py"""

# ------------------- DO NOT EDIT ----------------------
# This file was generated by `reflex/utils/pyi_generator.py`!
# ------------------------------------------------------
from collections.abc import Mapping, Sequence
from typing import Any, Literal, TypedDict

import reflex as rx
from reflex.components.component import NoSSRComponent
from reflex_base.event import (
    EventType,
    PointerEventInfo,
)
from reflex_base.vars.base import Var
from reflex_components_core.core.breakpoints import Breakpoints

_MAPCN_JS = rx.asset("mapcn.jsx", shared=True)
_MAPCN_CSS = rx.asset("mapcn.css", shared=True)
MAPCN_LIBRARY: str
MAPLIBRE_GL = "maplibre-gl@^6.3.0"

class LngLat(TypedDict):
    lng: float
    lat: float

class MapClickEvent(TypedDict):
    lng: float
    lat: float
    point: dict[str, float]

class MapViewport(TypedDict):
    center: list[float]
    zoom: float
    bearing: float
    pitch: float

class LocateCoords(TypedDict):
    longitude: float
    latitude: float

class GeoJSONFeature(TypedDict):
    type: str
    id: Any
    properties: dict[str, Any]
    geometry: dict[str, Any] | None
    source: str | None
    sourceLayer: str | None

class MapGeoJSONEvent(TypedDict):
    feature: GeoJSONFeature
    longitude: float
    latitude: float

class MapArcEvent(TypedDict):
    arc: dict[str, Any]
    longitude: float
    latitude: float

class MapcnComponent(NoSSRComponent):
    def add_imports(self) -> dict[str, str | list[str]]: ...
    @classmethod
    def create(
        cls,
        *children,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: EventType[()] | None = None,
        on_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_context_menu: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_double_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_focus: EventType[()] | None = None,
        on_mount: EventType[()] | None = None,
        on_mouse_down: EventType[()] | None = None,
        on_mouse_enter: EventType[()] | None = None,
        on_mouse_leave: EventType[()] | None = None,
        on_mouse_move: EventType[()] | None = None,
        on_mouse_out: EventType[()] | None = None,
        on_mouse_over: EventType[()] | None = None,
        on_mouse_up: EventType[()] | None = None,
        on_scroll: EventType[()] | None = None,
        on_scroll_end: EventType[()] | None = None,
        on_unmount: EventType[()] | None = None,
        **props,
    ) -> MapcnComponent:
        """Create the component.

        Args:
            *children: The children of the component.
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            **props: The props of the component.

        Returns:
            The component.
        """
        ...

class Map(MapcnComponent):
    @classmethod
    def create(
        cls,
        *children,
        theme: Literal["dark", "light"] | Var[Literal["dark", "light"]] | None = None,
        styles: Var[dict[str, Any]] | dict[str, Any] | None = None,
        blank: Var[bool] | bool | None = None,
        projection: Var[dict[str, Any]] | dict[str, Any] | None = None,
        viewport: Var[dict[str, Any]] | dict[str, Any] | None = None,
        loading: Var[bool] | bool | None = None,
        center: Var[list[float]] | list[float] | None = None,
        zoom: Var[float] | float | None = None,
        bearing: Var[float] | float | None = None,
        pitch: Var[float] | float | None = None,
        min_zoom: Var[float] | float | None = None,
        max_zoom: Var[float] | float | None = None,
        min_pitch: Var[float] | float | None = None,
        max_pitch: Var[float] | float | None = None,
        max_bounds: Var[list[list[float]]] | list[list[float]] | None = None,
        interactive: Var[bool] | bool | None = None,
        scroll_zoom: Var[bool] | bool | None = None,
        drag_pan: Var[bool] | bool | None = None,
        drag_rotate: Var[bool] | bool | None = None,
        double_click_zoom: Var[bool] | bool | None = None,
        touch_zoom_rotate: Var[bool] | bool | None = None,
        touch_pitch: Var[bool] | bool | None = None,
        keyboard: Var[bool] | bool | None = None,
        box_zoom: Var[bool] | bool | None = None,
        cooperative_gestures: Var[bool] | bool | None = None,
        hash: Var[bool | str] | bool | str | None = None,
        render_world_copies: Var[bool] | bool | None = None,
        fade_duration: Var[int] | int | None = None,
        pixel_ratio: Var[float] | float | None = None,
        canvas_context_attributes: Var[dict[str, Any]] | dict[str, Any] | None = None,
        attribution_control: Var[bool | dict[str, Any]]
        | bool
        | dict[str, Any]
        | None = None,
        locale: Var[dict[str, str]] | dict[str, str] | None = None,
        worker_url: Var[str] | str | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: EventType[()] | None = None,
        on_click: EventType[()] | EventType[MapClickEvent] | None = None,
        on_context_menu: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_double_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_focus: EventType[()] | None = None,
        on_load: EventType[()] | EventType[MapViewport] | None = None,
        on_mount: EventType[()] | None = None,
        on_mouse_down: EventType[()] | None = None,
        on_mouse_enter: EventType[()] | None = None,
        on_mouse_leave: EventType[()] | None = None,
        on_mouse_move: EventType[()] | None = None,
        on_mouse_out: EventType[()] | None = None,
        on_mouse_over: EventType[()] | None = None,
        on_mouse_up: EventType[()] | None = None,
        on_move_end: EventType[()] | EventType[MapViewport] | None = None,
        on_scroll: EventType[()] | None = None,
        on_scroll_end: EventType[()] | None = None,
        on_unmount: EventType[()] | None = None,
        on_viewport_change: EventType[()] | EventType[MapViewport] | None = None,
        **props,
    ) -> Map:
        """Create the component.

        Args:
            *children: The children of the component.
            theme: Force a theme instead of following the document / system preference.
            styles: Custom map styles per theme: {"light": url_or_spec, "dark": url_or_spec}.
            blank: Transparent, tile-less basemap for data visualisations.
            projection: Map projection, e.g. {"type": "globe"}.
            viewport: Controlled viewport: {"center": [lng, lat], "zoom", "bearing", "pitch"}. Use together with `on_viewport_change` for controlled mode.
            loading: Show a loading overlay on top of the map.
            center: Initial center as [longitude, latitude].
            zoom: no description
            bearing: no description
            pitch: no description
            min_zoom: no description
            max_zoom: no description
            min_pitch: no description
            max_pitch: no description
            max_bounds: [[west, south], [east, north]]
            interactive: no description
            scroll_zoom: no description
            drag_pan: no description
            drag_rotate: no description
            double_click_zoom: no description
            touch_zoom_rotate: no description
            touch_pitch: no description
            keyboard: no description
            box_zoom: no description
            cooperative_gestures: no description
            hash: no description
            render_world_copies: no description
            fade_duration: no description
            pixel_ratio: no description
            canvas_context_attributes: no description
            attribution_control: no description
            locale: no description
            worker_url: URL of the MapLibre web worker (defaults to unpkg CDN).
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fires when the base map is clicked (Reflex extra).
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            on_viewport_change: Fires continuously while the map moves (pan/zoom/rotate/pitch). Combine with `.throttle(ms)` to limit backend traffic.
            on_move_end: Fires once the camera settles (Reflex extra).
            on_load: Fires when MapLibre finished loading the style (Reflex extra).
            **props: The props of the component.

        Returns:
            The component.
        """
        ...

class MapMarker(MapcnComponent):
    @classmethod
    def create(
        cls,
        *children,
        longitude: Var[float] | float | None = None,
        latitude: Var[float] | float | None = None,
        draggable: Var[bool] | bool | None = None,
        anchor: Literal[
            "bottom",
            "bottom-left",
            "bottom-right",
            "center",
            "left",
            "right",
            "top",
            "top-left",
            "top-right",
        ]
        | Var[
            Literal[
                "bottom",
                "bottom-left",
                "bottom-right",
                "center",
                "left",
                "right",
                "top",
                "top-left",
                "top-right",
            ]
        ]
        | None = None,
        offset: Var[list[float]] | list[float] | None = None,
        rotation: Var[float] | float | None = None,
        rotation_alignment: Literal["auto", "map", "viewport"]
        | Var[Literal["auto", "map", "viewport"]]
        | None = None,
        pitch_alignment: Literal["auto", "map", "viewport"]
        | Var[Literal["auto", "map", "viewport"]]
        | None = None,
        opacity: Var[str] | str | None = None,
        opacity_when_covered: Var[str] | str | None = None,
        click_tolerance: Var[int] | int | None = None,
        subpixel_positioning: Var[bool] | bool | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: EventType[()] | None = None,
        on_click: EventType[()] | EventType[LngLat] | None = None,
        on_context_menu: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_double_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_drag: EventType[()] | EventType[LngLat] | None = None,
        on_drag_end: EventType[()] | EventType[LngLat] | None = None,
        on_drag_start: EventType[()] | EventType[LngLat] | None = None,
        on_focus: EventType[()] | None = None,
        on_mount: EventType[()] | None = None,
        on_mouse_down: EventType[()] | None = None,
        on_mouse_enter: EventType[()] | EventType[LngLat] | None = None,
        on_mouse_leave: EventType[()] | EventType[LngLat] | None = None,
        on_mouse_move: EventType[()] | None = None,
        on_mouse_out: EventType[()] | None = None,
        on_mouse_over: EventType[()] | None = None,
        on_mouse_up: EventType[()] | None = None,
        on_scroll: EventType[()] | None = None,
        on_scroll_end: EventType[()] | None = None,
        on_unmount: EventType[()] | None = None,
        **props,
    ) -> MapMarker:
        """Create the component.

        Args:
            *children: The children of the component.
            longitude: no description
            latitude: no description
            draggable: Enable dragging (fires on_drag_start / on_drag / on_drag_end).
            anchor: ---- MapLibre MarkerOptions -----------------------------------------
            offset: no description
            rotation: no description
            rotation_alignment: no description
            pitch_alignment: no description
            opacity: no description
            opacity_when_covered: no description
            click_tolerance: no description
            subpixel_positioning: no description
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: ---- Events (each receives {"lng": float, "lat": float}) ------------
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            on_drag_start: no description
            on_drag: no description
            on_drag_end: no description
            **props: The props of the component.

        Returns:
            The component.
        """
        ...

class MarkerContent(MapcnComponent):
    @classmethod
    def create(
        cls,
        *children,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: EventType[()] | None = None,
        on_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_context_menu: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_double_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_focus: EventType[()] | None = None,
        on_mount: EventType[()] | None = None,
        on_mouse_down: EventType[()] | None = None,
        on_mouse_enter: EventType[()] | None = None,
        on_mouse_leave: EventType[()] | None = None,
        on_mouse_move: EventType[()] | None = None,
        on_mouse_out: EventType[()] | None = None,
        on_mouse_over: EventType[()] | None = None,
        on_mouse_up: EventType[()] | None = None,
        on_scroll: EventType[()] | None = None,
        on_scroll_end: EventType[()] | None = None,
        on_unmount: EventType[()] | None = None,
        **props,
    ) -> MarkerContent:
        """Create the component.

        Args:
            *children: The children of the component.
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            **props: The props of the component.

        Returns:
            The component.
        """
        ...

class MarkerPopup(MapcnComponent):
    @classmethod
    def create(
        cls,
        *children,
        close_button: Var[bool] | bool | None = None,
        offset: Var[dict[str, list[float]] | int | list[float]]
        | dict[str, list[float]]
        | int
        | list[float]
        | None = None,
        max_width: Var[str] | str | None = None,
        anchor: Var[str] | str | None = None,
        close_on_click: Var[bool] | bool | None = None,
        close_on_move: Var[bool] | bool | None = None,
        focus_after_open: Var[bool] | bool | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: EventType[()] | None = None,
        on_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_context_menu: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_double_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_focus: EventType[()] | None = None,
        on_mount: EventType[()] | None = None,
        on_mouse_down: EventType[()] | None = None,
        on_mouse_enter: EventType[()] | None = None,
        on_mouse_leave: EventType[()] | None = None,
        on_mouse_move: EventType[()] | None = None,
        on_mouse_out: EventType[()] | None = None,
        on_mouse_over: EventType[()] | None = None,
        on_mouse_up: EventType[()] | None = None,
        on_scroll: EventType[()] | None = None,
        on_scroll_end: EventType[()] | None = None,
        on_unmount: EventType[()] | None = None,
        **props,
    ) -> MarkerPopup:
        """Create the component.

        Args:
            *children: The children of the component.
            close_button: Render an explicit close button.
            offset: ---- MapLibre PopupOptions ------------------------------------------
            max_width: no description
            anchor: no description
            close_on_click: no description
            close_on_move: no description
            focus_after_open: no description
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            **props: The props of the component.

        Returns:
            The component.
        """
        ...

class MarkerTooltip(MapcnComponent):
    @classmethod
    def create(
        cls,
        *children,
        offset: Var[dict[str, list[float]] | int | list[float]]
        | dict[str, list[float]]
        | int
        | list[float]
        | None = None,
        max_width: Var[str] | str | None = None,
        anchor: Var[str] | str | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: EventType[()] | None = None,
        on_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_context_menu: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_double_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_focus: EventType[()] | None = None,
        on_mount: EventType[()] | None = None,
        on_mouse_down: EventType[()] | None = None,
        on_mouse_enter: EventType[()] | None = None,
        on_mouse_leave: EventType[()] | None = None,
        on_mouse_move: EventType[()] | None = None,
        on_mouse_out: EventType[()] | None = None,
        on_mouse_over: EventType[()] | None = None,
        on_mouse_up: EventType[()] | None = None,
        on_scroll: EventType[()] | None = None,
        on_scroll_end: EventType[()] | None = None,
        on_unmount: EventType[()] | None = None,
        **props,
    ) -> MarkerTooltip:
        """Create the component.

        Args:
            *children: The children of the component.
            offset: no description
            max_width: no description
            anchor: no description
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            **props: The props of the component.

        Returns:
            The component.
        """
        ...

class MarkerLabel(MapcnComponent):
    @classmethod
    def create(
        cls,
        *children,
        position: Literal["bottom", "top"]
        | Var[Literal["bottom", "top"]]
        | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: EventType[()] | None = None,
        on_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_context_menu: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_double_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_focus: EventType[()] | None = None,
        on_mount: EventType[()] | None = None,
        on_mouse_down: EventType[()] | None = None,
        on_mouse_enter: EventType[()] | None = None,
        on_mouse_leave: EventType[()] | None = None,
        on_mouse_move: EventType[()] | None = None,
        on_mouse_out: EventType[()] | None = None,
        on_mouse_over: EventType[()] | None = None,
        on_mouse_up: EventType[()] | None = None,
        on_scroll: EventType[()] | None = None,
        on_scroll_end: EventType[()] | None = None,
        on_unmount: EventType[()] | None = None,
        **props,
    ) -> MarkerLabel:
        """Create the component.

        Args:
            *children: The children of the component.
            position: no description
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            **props: The props of the component.

        Returns:
            The component.
        """
        ...

class MapPopup(MapcnComponent):
    @classmethod
    def create(
        cls,
        *children,
        longitude: Var[float] | float | None = None,
        latitude: Var[float] | float | None = None,
        close_button: Var[bool] | bool | None = None,
        offset: Var[dict[str, list[float]] | int | list[float]]
        | dict[str, list[float]]
        | int
        | list[float]
        | None = None,
        max_width: Var[str] | str | None = None,
        anchor: Var[str] | str | None = None,
        close_on_click: Var[bool] | bool | None = None,
        close_on_move: Var[bool] | bool | None = None,
        focus_after_open: Var[bool] | bool | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: EventType[()] | None = None,
        on_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_close: EventType[()] | None = None,
        on_context_menu: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_double_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_focus: EventType[()] | None = None,
        on_mount: EventType[()] | None = None,
        on_mouse_down: EventType[()] | None = None,
        on_mouse_enter: EventType[()] | None = None,
        on_mouse_leave: EventType[()] | None = None,
        on_mouse_move: EventType[()] | None = None,
        on_mouse_out: EventType[()] | None = None,
        on_mouse_over: EventType[()] | None = None,
        on_mouse_up: EventType[()] | None = None,
        on_scroll: EventType[()] | None = None,
        on_scroll_end: EventType[()] | None = None,
        on_unmount: EventType[()] | None = None,
        **props,
    ) -> MapPopup:
        """Create the component.

        Args:
            *children: The children of the component.
            longitude: no description
            latitude: no description
            close_button: no description
            offset: ---- MapLibre PopupOptions ------------------------------------------
            max_width: no description
            anchor: no description
            close_on_click: no description
            close_on_move: no description
            focus_after_open: no description
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            on_close: Fires when the popup is closed (close button, outside click, ...).
            **props: The props of the component.

        Returns:
            The component.
        """
        ...

class MapControls(MapcnComponent):
    @classmethod
    def create(
        cls,
        *children,
        position: Literal["bottom-left", "bottom-right", "top-left", "top-right"]
        | Var[Literal["bottom-left", "bottom-right", "top-left", "top-right"]]
        | None = None,
        show_zoom: Var[bool] | bool | None = None,
        show_compass: Var[bool] | bool | None = None,
        show_locate: Var[bool] | bool | None = None,
        show_fullscreen: Var[bool] | bool | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: EventType[()] | None = None,
        on_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_context_menu: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_double_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_focus: EventType[()] | None = None,
        on_locate: EventType[()] | EventType[LocateCoords] | None = None,
        on_mount: EventType[()] | None = None,
        on_mouse_down: EventType[()] | None = None,
        on_mouse_enter: EventType[()] | None = None,
        on_mouse_leave: EventType[()] | None = None,
        on_mouse_move: EventType[()] | None = None,
        on_mouse_out: EventType[()] | None = None,
        on_mouse_over: EventType[()] | None = None,
        on_mouse_up: EventType[()] | None = None,
        on_scroll: EventType[()] | None = None,
        on_scroll_end: EventType[()] | None = None,
        on_unmount: EventType[()] | None = None,
        **props,
    ) -> MapControls:
        """Create the component.

        Args:
            *children: The children of the component.
            position: no description
            show_zoom: no description
            show_compass: no description
            show_locate: no description
            show_fullscreen: no description
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            on_locate: Receives {"longitude": float, "latitude": float} after geolocation.
            **props: The props of the component.

        Returns:
            The component.
        """
        ...

class MapRoute(MapcnComponent):
    @classmethod
    def create(
        cls,
        *children,
        coordinates: Var[list[list[float]]] | list[list[float]] | None = None,
        color: Var[str] | str | None = None,
        width: Var[float] | float | None = None,
        opacity: Var[float] | float | None = None,
        dash_array: Var[list[float]] | list[float] | None = None,
        progress: Var[float] | float | None = None,
        active: Var[bool] | bool | None = None,
        active_color: Var[str] | str | None = None,
        active_width: Var[float] | float | None = None,
        active_opacity: Var[float] | float | None = None,
        active_dash_array: Var[list[float]] | list[float] | None = None,
        before_id: Var[str] | str | None = None,
        interactive: Var[bool] | bool | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: EventType[()] | None = None,
        on_click: EventType[()] | EventType[LngLat] | None = None,
        on_context_menu: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_double_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_focus: EventType[()] | None = None,
        on_mount: EventType[()] | None = None,
        on_mouse_down: EventType[()] | None = None,
        on_mouse_enter: EventType[()] | EventType[LngLat] | None = None,
        on_mouse_leave: EventType[()] | None = None,
        on_mouse_move: EventType[()] | None = None,
        on_mouse_out: EventType[()] | None = None,
        on_mouse_over: EventType[()] | None = None,
        on_mouse_up: EventType[()] | None = None,
        on_scroll: EventType[()] | None = None,
        on_scroll_end: EventType[()] | None = None,
        on_unmount: EventType[()] | None = None,
        **props,
    ) -> MapRoute:
        """Create the component.

        Args:
            *children: The children of the component.
            coordinates: Explicit layer id (auto-generated when omitted).
            color: no description
            width: no description
            opacity: no description
            dash_array: no description
            progress: Fraction (0-1) of the route already covered.
            active: no description
            active_color: no description
            active_width: no description
            active_opacity: no description
            active_dash_array: no description
            before_id: no description
            interactive: no description
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            **props: The props of the component.

        Returns:
            The component.
        """
        ...

class RouteProgress(MapcnComponent):
    @classmethod
    def create(
        cls,
        *children,
        color: Var[str] | str | None = None,
        width: Var[float] | float | None = None,
        opacity: Var[float] | float | None = None,
        dash_array: Var[list[float]] | list[float] | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: EventType[()] | None = None,
        on_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_context_menu: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_double_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_focus: EventType[()] | None = None,
        on_mount: EventType[()] | None = None,
        on_mouse_down: EventType[()] | None = None,
        on_mouse_enter: EventType[()] | None = None,
        on_mouse_leave: EventType[()] | None = None,
        on_mouse_move: EventType[()] | None = None,
        on_mouse_out: EventType[()] | None = None,
        on_mouse_over: EventType[()] | None = None,
        on_mouse_up: EventType[()] | None = None,
        on_scroll: EventType[()] | None = None,
        on_scroll_end: EventType[()] | None = None,
        on_unmount: EventType[()] | None = None,
        **props,
    ) -> RouteProgress:
        """Create the component.

        Args:
            *children: The children of the component.
            color: no description
            width: no description
            opacity: no description
            dash_array: no description
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            **props: The props of the component.

        Returns:
            The component.
        """
        ...

class RouteMarker(MapMarker):
    @classmethod
    def create(
        cls,
        *children,
        at: Var[float | str] | float | str | None = None,
        longitude: Var[float] | float | None = None,
        latitude: Var[float] | float | None = None,
        draggable: Var[bool] | bool | None = None,
        anchor: Literal[
            "bottom",
            "bottom-left",
            "bottom-right",
            "center",
            "left",
            "right",
            "top",
            "top-left",
            "top-right",
        ]
        | Var[
            Literal[
                "bottom",
                "bottom-left",
                "bottom-right",
                "center",
                "left",
                "right",
                "top",
                "top-left",
                "top-right",
            ]
        ]
        | None = None,
        offset: Var[list[float]] | list[float] | None = None,
        rotation: Var[float] | float | None = None,
        rotation_alignment: Literal["auto", "map", "viewport"]
        | Var[Literal["auto", "map", "viewport"]]
        | None = None,
        pitch_alignment: Literal["auto", "map", "viewport"]
        | Var[Literal["auto", "map", "viewport"]]
        | None = None,
        opacity: Var[str] | str | None = None,
        opacity_when_covered: Var[str] | str | None = None,
        click_tolerance: Var[int] | int | None = None,
        subpixel_positioning: Var[bool] | bool | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: EventType[()] | None = None,
        on_click: EventType[()] | EventType[LngLat] | None = None,
        on_context_menu: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_double_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_drag: EventType[()] | EventType[LngLat] | None = None,
        on_drag_end: EventType[()] | EventType[LngLat] | None = None,
        on_drag_start: EventType[()] | EventType[LngLat] | None = None,
        on_focus: EventType[()] | None = None,
        on_mount: EventType[()] | None = None,
        on_mouse_down: EventType[()] | None = None,
        on_mouse_enter: EventType[()] | EventType[LngLat] | None = None,
        on_mouse_leave: EventType[()] | EventType[LngLat] | None = None,
        on_mouse_move: EventType[()] | None = None,
        on_mouse_out: EventType[()] | None = None,
        on_mouse_over: EventType[()] | None = None,
        on_mouse_up: EventType[()] | None = None,
        on_scroll: EventType[()] | None = None,
        on_scroll_end: EventType[()] | None = None,
        on_unmount: EventType[()] | None = None,
        **props,
    ) -> RouteMarker:
        """Create the component.

        Args:
            *children: The children of the component.
            at: no description
            longitude: no description
            latitude: no description
            draggable: Enable dragging (fires on_drag_start / on_drag / on_drag_end).
            anchor: ---- MapLibre MarkerOptions -----------------------------------------
            offset: no description
            rotation: no description
            rotation_alignment: no description
            pitch_alignment: no description
            opacity: no description
            opacity_when_covered: no description
            click_tolerance: no description
            subpixel_positioning: no description
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: ---- Events (each receives {"lng": float, "lat": float}) ------------
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            on_drag_start: no description
            on_drag: no description
            on_drag_end: no description
            **props: The props of the component.

        Returns:
            The component.
        """
        ...

class MapArc(MapcnComponent):
    @classmethod
    def create(
        cls,
        *children,
        data: Var[list[dict[str, Any]]] | list[dict[str, Any]] | None = None,
        curvature: Var[float] | float | None = None,
        samples: Var[int] | int | None = None,
        paint: Var[dict[str, Any]] | dict[str, Any] | None = None,
        layout: Var[dict[str, Any]] | dict[str, Any] | None = None,
        hover_paint: Var[dict[str, Any]] | dict[str, Any] | None = None,
        interactive: Var[bool] | bool | None = None,
        before_id: Var[str] | str | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: EventType[()] | None = None,
        on_click: EventType[()] | EventType[MapArcEvent] | None = None,
        on_context_menu: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_double_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_focus: EventType[()] | None = None,
        on_hover: EventType[()] | EventType[MapArcEvent] | None = None,
        on_mount: EventType[()] | None = None,
        on_mouse_down: EventType[()] | None = None,
        on_mouse_enter: EventType[()] | None = None,
        on_mouse_leave: EventType[()] | None = None,
        on_mouse_move: EventType[()] | None = None,
        on_mouse_out: EventType[()] | None = None,
        on_mouse_over: EventType[()] | None = None,
        on_mouse_up: EventType[()] | None = None,
        on_scroll: EventType[()] | None = None,
        on_scroll_end: EventType[()] | None = None,
        on_unmount: EventType[()] | None = None,
        **props,
    ) -> MapArc:
        """Create the component.

        Args:
            *children: The children of the component.
            data: no description
            curvature: no description
            samples: no description
            paint: no description
            layout: no description
            hover_paint: no description
            interactive: no description
            before_id: no description
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            on_hover: Receives the event or None when the cursor leaves the last hovered arc.
            **props: The props of the component.

        Returns:
            The component.
        """
        ...

class MapGeoJSON(MapcnComponent):
    @classmethod
    def create(
        cls,
        *children,
        data: Var[dict[str, Any] | str] | dict[str, Any] | str | None = None,
        promote_id: Var[str] | str | None = None,
        fill_paint: Var[bool | dict[str, Any]] | bool | dict[str, Any] | None = None,
        line_paint: Var[bool | dict[str, Any]] | bool | dict[str, Any] | None = None,
        fill_hover_paint: Var[dict[str, Any]] | dict[str, Any] | None = None,
        interactive: Var[bool] | bool | None = None,
        before_id: Var[str] | str | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: EventType[()] | None = None,
        on_click: EventType[()] | EventType[MapGeoJSONEvent] | None = None,
        on_context_menu: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_double_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_focus: EventType[()] | None = None,
        on_hover: EventType[()] | EventType[MapGeoJSONEvent] | None = None,
        on_mount: EventType[()] | None = None,
        on_mouse_down: EventType[()] | None = None,
        on_mouse_enter: EventType[()] | None = None,
        on_mouse_leave: EventType[()] | None = None,
        on_mouse_move: EventType[()] | None = None,
        on_mouse_out: EventType[()] | None = None,
        on_mouse_over: EventType[()] | None = None,
        on_mouse_up: EventType[()] | None = None,
        on_scroll: EventType[()] | None = None,
        on_scroll_end: EventType[()] | None = None,
        on_unmount: EventType[()] | None = None,
        **props,
    ) -> MapGeoJSON:
        """Create the component.

        Args:
            *children: The children of the component.
            data: no description
            promote_id: Feature property promoted to the feature id (needed for hover state).
            fill_paint: Paint for the fill layer, or False to omit it.
            line_paint: Paint for the outline layer, or False to omit it.
            fill_hover_paint: no description
            interactive: no description
            before_id: no description
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            on_hover: Receives the event or None when the cursor leaves.
            **props: The props of the component.

        Returns:
            The component.
        """
        ...

class MapClusterLayer(MapcnComponent):
    @classmethod
    def create(
        cls,
        *children,
        data: Var[dict[str, Any] | str] | dict[str, Any] | str | None = None,
        cluster_max_zoom: Var[int] | int | None = None,
        cluster_radius: Var[int] | int | None = None,
        cluster_colors: Var[list[str]] | list[str] | None = None,
        cluster_thresholds: Var[list[int]] | list[int] | None = None,
        point_color: Var[str] | str | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: EventType[()] | None = None,
        on_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_cluster_click: EventType[()] | EventType[int] | EventType[int, list] | EventType[int, list, int] | None = None,
        on_context_menu: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_double_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_focus: EventType[()] | None = None,
        on_mount: EventType[()] | None = None,
        on_mouse_down: EventType[()] | None = None,
        on_mouse_enter: EventType[()] | None = None,
        on_mouse_leave: EventType[()] | None = None,
        on_mouse_move: EventType[()] | None = None,
        on_mouse_out: EventType[()] | None = None,
        on_mouse_over: EventType[()] | None = None,
        on_mouse_up: EventType[()] | None = None,
        on_point_click: EventType[()] | EventType[GeoJSONFeature] | EventType[GeoJSONFeature, list] | None = None,
        on_scroll: EventType[()] | None = None,
        on_scroll_end: EventType[()] | None = None,
        on_unmount: EventType[()] | None = None,
        **props,
    ) -> MapClusterLayer:
        """Create the component.

        Args:
            *children: The children of the component.
            data: no description
            cluster_max_zoom: no description
            cluster_radius: no description
            cluster_colors: [small, medium, large]
            cluster_thresholds: [medium, large]
            point_color: no description
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            on_point_click: (feature, [lng, lat])
            on_cluster_click: (cluster_id, [lng, lat], point_count). Overrides the default zoom-in.
            **props: The props of the component.

        Returns:
            The component.
        """
        ...

class MapCamera(MapcnComponent):
    @classmethod
    def create(
        cls,
        *children,
        command: Var[dict[str, Any]] | dict[str, Any] | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: EventType[()] | None = None,
        on_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_context_menu: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_double_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_focus: EventType[()] | None = None,
        on_mount: EventType[()] | None = None,
        on_mouse_down: EventType[()] | None = None,
        on_mouse_enter: EventType[()] | None = None,
        on_mouse_leave: EventType[()] | None = None,
        on_mouse_move: EventType[()] | None = None,
        on_mouse_out: EventType[()] | None = None,
        on_mouse_over: EventType[()] | None = None,
        on_mouse_up: EventType[()] | None = None,
        on_scroll: EventType[()] | None = None,
        on_scroll_end: EventType[()] | None = None,
        on_unmount: EventType[()] | None = None,
        **props,
    ) -> MapCamera:
        """Create the component.

        Args:
            *children: The children of the component.
            command: no description
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            **props: The props of the component.

        Returns:
            The component.
        """
        ...

def camera_command(
    type: str = "flyTo", *, seq: int | None = None, **options: Any
) -> dict[str, Any]: ...

map = Map.create
map_marker = MapMarker.create
marker_content = MarkerContent.create
marker_popup = MarkerPopup.create
marker_tooltip = MarkerTooltip.create
marker_label = MarkerLabel.create
map_popup = MapPopup.create
map_controls = MapControls.create
map_route = MapRoute.create
route_progress = RouteProgress.create
route_marker = RouteMarker.create
map_arc = MapArc.create
map_geojson = MapGeoJSON.create
map_cluster_layer = MapClusterLayer.create
map_camera = MapCamera.create

class MapcnNamespace(rx.ComponentNamespace):
    map = staticmethod(Map.create)
    marker = staticmethod(MapMarker.create)
    marker_content = staticmethod(MarkerContent.create)
    marker_popup = staticmethod(MarkerPopup.create)
    marker_tooltip = staticmethod(MarkerTooltip.create)
    marker_label = staticmethod(MarkerLabel.create)
    popup = staticmethod(MapPopup.create)
    controls = staticmethod(MapControls.create)
    route = staticmethod(MapRoute.create)
    route_progress = staticmethod(RouteProgress.create)
    route_marker = staticmethod(RouteMarker.create)
    arc = staticmethod(MapArc.create)
    geojson = staticmethod(MapGeoJSON.create)
    cluster_layer = staticmethod(MapClusterLayer.create)
    camera = staticmethod(MapCamera.create)

    @staticmethod
    def __call__(
        *children,
        theme: Literal["dark", "light"] | Var[Literal["dark", "light"]] | None = None,
        styles: Var[dict[str, Any]] | dict[str, Any] | None = None,
        blank: Var[bool] | bool | None = None,
        projection: Var[dict[str, Any]] | dict[str, Any] | None = None,
        viewport: Var[dict[str, Any]] | dict[str, Any] | None = None,
        loading: Var[bool] | bool | None = None,
        center: Var[list[float]] | list[float] | None = None,
        zoom: Var[float] | float | None = None,
        bearing: Var[float] | float | None = None,
        pitch: Var[float] | float | None = None,
        min_zoom: Var[float] | float | None = None,
        max_zoom: Var[float] | float | None = None,
        min_pitch: Var[float] | float | None = None,
        max_pitch: Var[float] | float | None = None,
        max_bounds: Var[list[list[float]]] | list[list[float]] | None = None,
        interactive: Var[bool] | bool | None = None,
        scroll_zoom: Var[bool] | bool | None = None,
        drag_pan: Var[bool] | bool | None = None,
        drag_rotate: Var[bool] | bool | None = None,
        double_click_zoom: Var[bool] | bool | None = None,
        touch_zoom_rotate: Var[bool] | bool | None = None,
        touch_pitch: Var[bool] | bool | None = None,
        keyboard: Var[bool] | bool | None = None,
        box_zoom: Var[bool] | bool | None = None,
        cooperative_gestures: Var[bool] | bool | None = None,
        hash: Var[bool | str] | bool | str | None = None,
        render_world_copies: Var[bool] | bool | None = None,
        fade_duration: Var[int] | int | None = None,
        pixel_ratio: Var[float] | float | None = None,
        canvas_context_attributes: Var[dict[str, Any]] | dict[str, Any] | None = None,
        attribution_control: Var[bool | dict[str, Any]]
        | bool
        | dict[str, Any]
        | None = None,
        locale: Var[dict[str, str]] | dict[str, str] | None = None,
        worker_url: Var[str] | str | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: EventType[()] | None = None,
        on_click: EventType[()] | EventType[MapClickEvent] | None = None,
        on_context_menu: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_double_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_focus: EventType[()] | None = None,
        on_load: EventType[()] | EventType[MapViewport] | None = None,
        on_mount: EventType[()] | None = None,
        on_mouse_down: EventType[()] | None = None,
        on_mouse_enter: EventType[()] | None = None,
        on_mouse_leave: EventType[()] | None = None,
        on_mouse_move: EventType[()] | None = None,
        on_mouse_out: EventType[()] | None = None,
        on_mouse_over: EventType[()] | None = None,
        on_mouse_up: EventType[()] | None = None,
        on_move_end: EventType[()] | EventType[MapViewport] | None = None,
        on_scroll: EventType[()] | None = None,
        on_scroll_end: EventType[()] | None = None,
        on_unmount: EventType[()] | None = None,
        on_viewport_change: EventType[()] | EventType[MapViewport] | None = None,
        **props,
    ) -> Map:
        """Create the component.

        Args:
            *children: The children of the component.
            theme: Force a theme instead of following the document / system preference.
            styles: Custom map styles per theme: {"light": url_or_spec, "dark": url_or_spec}.
            blank: Transparent, tile-less basemap for data visualisations.
            projection: Map projection, e.g. {"type": "globe"}.
            viewport: Controlled viewport: {"center": [lng, lat], "zoom", "bearing", "pitch"}. Use together with `on_viewport_change` for controlled mode.
            loading: Show a loading overlay on top of the map.
            center: Initial center as [longitude, latitude].
            zoom: no description
            bearing: no description
            pitch: no description
            min_zoom: no description
            max_zoom: no description
            min_pitch: no description
            max_pitch: no description
            max_bounds: [[west, south], [east, north]]
            interactive: no description
            scroll_zoom: no description
            drag_pan: no description
            drag_rotate: no description
            double_click_zoom: no description
            touch_zoom_rotate: no description
            touch_pitch: no description
            keyboard: no description
            box_zoom: no description
            cooperative_gestures: no description
            hash: no description
            render_world_copies: no description
            fade_duration: no description
            pixel_ratio: no description
            canvas_context_attributes: no description
            attribution_control: no description
            locale: no description
            worker_url: URL of the MapLibre web worker (defaults to unpkg CDN).
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fires when the base map is clicked (Reflex extra).
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            on_viewport_change: Fires continuously while the map moves (pan/zoom/rotate/pitch). Combine with `.throttle(ms)` to limit backend traffic.
            on_move_end: Fires once the camera settles (Reflex extra).
            on_load: Fires when MapLibre finished loading the style (Reflex extra).
            **props: The props of the component.

        Returns:
            The component.
        """
        ...

mapcn = MapcnNamespace()
__all__ = [
    "MAPLIBRE_GL",
    "GeoJSONFeature",
    "LngLat",
    "LocateCoords",
    "Map",
    "MapArc",
    "MapArcEvent",
    "MapCamera",
    "MapClickEvent",
    "MapClusterLayer",
    "MapControls",
    "MapGeoJSON",
    "MapGeoJSONEvent",
    "MapMarker",
    "MapPopup",
    "MapRoute",
    "MapViewport",
    "MapcnComponent",
    "MapcnNamespace",
    "MarkerContent",
    "MarkerLabel",
    "MarkerPopup",
    "MarkerTooltip",
    "RouteMarker",
    "RouteProgress",
    "camera_command",
    "map",
    "map_arc",
    "map_camera",
    "map_cluster_layer",
    "map_controls",
    "map_geojson",
    "map_marker",
    "map_popup",
    "map_route",
    "mapcn",
    "marker_content",
    "marker_label",
    "marker_popup",
    "marker_tooltip",
    "route_marker",
    "route_progress",
]
